// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv_16_32_10_s_HH_
#define _conv_16_32_10_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "conv_16_32_10_s_tdEe.h"
#include "conv_16_32_10_s_weOg.h"

namespace ap_rtl {

struct conv_16_32_10_s : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<11> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<1> > input_r_q0;
    sc_out< sc_lv<11> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<1> > output_r_d0;


    // Module declarations
    conv_16_32_10_s(sc_module_name name);
    SC_HAS_PROCESS(conv_16_32_10_s);

    ~conv_16_32_10_s();

    sc_trace_file* mVcdFile;

    conv_16_32_10_s_tdEe* threshold_conv2_V_U;
    conv_16_32_10_s_weOg* w_conv2_U;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > threshold_conv2_V_address0;
    sc_signal< sc_logic > threshold_conv2_V_ce0;
    sc_signal< sc_lv<5> > threshold_conv2_V_q0;
    sc_signal< sc_lv<13> > w_conv2_address0;
    sc_signal< sc_logic > w_conv2_ce0;
    sc_signal< sc_lv<1> > w_conv2_q0;
    sc_signal< sc_lv<6> > n_fu_237_p2;
    sc_signal< sc_lv<6> > n_reg_582;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln61_fu_231_p2;
    sc_signal< sc_lv<11> > zext_ln73_fu_248_p1;
    sc_signal< sc_lv<11> > zext_ln73_reg_592;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<10> > zext_ln895_fu_260_p1;
    sc_signal< sc_lv<10> > zext_ln895_reg_597;
    sc_signal< sc_lv<16> > sext_ln62_fu_264_p1;
    sc_signal< sc_lv<16> > sext_ln62_reg_602;
    sc_signal< sc_lv<4> > x_fu_274_p2;
    sc_signal< sc_lv<4> > x_reg_610;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<13> > zext_ln63_fu_280_p1;
    sc_signal< sc_lv<13> > zext_ln63_reg_615;
    sc_signal< sc_lv<1> > icmp_ln62_fu_268_p2;
    sc_signal< sc_lv<4> > y_fu_290_p2;
    sc_signal< sc_lv<4> > y_reg_623;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > c_fu_306_p2;
    sc_signal< sc_lv<2> > c_reg_631;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<12> > zext_ln68_1_fu_318_p1;
    sc_signal< sc_lv<12> > zext_ln68_1_reg_636;
    sc_signal< sc_lv<1> > icmp_ln65_fu_300_p2;
    sc_signal< sc_lv<14> > zext_ln66_1_fu_322_p1;
    sc_signal< sc_lv<14> > zext_ln66_1_reg_641;
    sc_signal< sc_lv<2> > r_fu_381_p2;
    sc_signal< sc_lv<2> > r_reg_649;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<9> > zext_ln68_2_fu_393_p1;
    sc_signal< sc_lv<9> > zext_ln68_2_reg_654;
    sc_signal< sc_lv<1> > icmp_ln66_fu_375_p2;
    sc_signal< sc_lv<64> > zext_ln68_3_fu_397_p1;
    sc_signal< sc_lv<64> > zext_ln68_3_reg_659;
    sc_signal< sc_lv<5> > m_fu_407_p2;
    sc_signal< sc_lv<5> > m_reg_667;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<14> > trunc_ln68_fu_457_p1;
    sc_signal< sc_lv<14> > trunc_ln68_reg_672;
    sc_signal< sc_lv<1> > icmp_ln67_fu_401_p2;
    sc_signal< sc_lv<12> > trunc_ln68_1_fu_461_p1;
    sc_signal< sc_lv<12> > trunc_ln68_1_reg_677;
    sc_signal< sc_lv<12> > add_ln68_8_fu_526_p2;
    sc_signal< sc_lv<12> > add_ln68_8_reg_682;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<16> > accum_V_1_fu_573_p2;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<6> > n_0_reg_126;
    sc_signal< sc_lv<4> > x_0_reg_138;
    sc_signal< sc_lv<1> > icmp_ln63_fu_284_p2;
    sc_signal< sc_lv<4> > y_0_reg_150;
    sc_signal< sc_lv<16> > p_014_0_reg_162;
    sc_signal< sc_lv<2> > c_0_reg_174;
    sc_signal< sc_lv<16> > p_014_1_reg_185;
    sc_signal< sc_lv<2> > r_0_reg_197;
    sc_signal< sc_lv<16> > p_014_2_reg_208;
    sc_signal< sc_lv<5> > m_0_reg_220;
    sc_signal< sc_lv<64> > zext_ln68_fu_243_p1;
    sc_signal< sc_lv<64> > zext_ln73_2_fu_366_p1;
    sc_signal< sc_lv<64> > zext_ln68_7_fu_548_p1;
    sc_signal< sc_lv<64> > zext_ln68_11_fu_553_p1;
    sc_signal< sc_lv<9> > tmp_fu_252_p3;
    sc_signal< sc_lv<4> > zext_ln65_fu_296_p1;
    sc_signal< sc_lv<4> > add_ln68_fu_312_p2;
    sc_signal< sc_lv<16> > shl_ln1503_fu_326_p2;
    sc_signal< sc_lv<16> > accum_V_fu_332_p2;
    sc_signal< sc_lv<10> > zext_ln73_1_fu_344_p1;
    sc_signal< sc_lv<10> > add_ln73_fu_348_p2;
    sc_signal< sc_lv<13> > tmp_25_cast_fu_353_p3;
    sc_signal< sc_lv<13> > add_ln73_1_fu_361_p2;
    sc_signal< sc_lv<4> > zext_ln66_fu_371_p1;
    sc_signal< sc_lv<4> > add_ln68_1_fu_387_p2;
    sc_signal< sc_lv<10> > tmp_s_fu_413_p3;
    sc_signal< sc_lv<11> > zext_ln68_4_fu_421_p1;
    sc_signal< sc_lv<11> > add_ln68_2_fu_425_p2;
    sc_signal< sc_lv<13> > tmp_3_fu_434_p3;
    sc_signal< sc_lv<64> > zext_ln68_6_fu_442_p1;
    sc_signal< sc_lv<64> > zext_ln68_5_fu_430_p1;
    sc_signal< sc_lv<64> > sub_ln68_fu_446_p2;
    sc_signal< sc_lv<64> > add_ln68_3_fu_452_p2;
    sc_signal< sc_lv<8> > tmp_1_fu_465_p3;
    sc_signal< sc_lv<6> > tmp_2_fu_477_p3;
    sc_signal< sc_lv<9> > zext_ln68_9_fu_485_p1;
    sc_signal< sc_lv<9> > zext_ln68_8_fu_473_p1;
    sc_signal< sc_lv<9> > add_ln68_5_fu_489_p2;
    sc_signal< sc_lv<9> > add_ln68_6_fu_495_p2;
    sc_signal< sc_lv<10> > tmp_4_fu_508_p3;
    sc_signal< sc_lv<12> > zext_ln68_10_fu_516_p1;
    sc_signal< sc_lv<12> > p_shl_cast_fu_500_p3;
    sc_signal< sc_lv<12> > add_ln68_7_fu_520_p2;
    sc_signal< sc_lv<14> > p_shl4_cast_fu_531_p3;
    sc_signal< sc_lv<14> > sub_ln68_1_fu_538_p2;
    sc_signal< sc_lv<14> > add_ln68_4_fu_543_p2;
    sc_signal< sc_lv<1> > xor_ln68_fu_557_p2;
    sc_signal< sc_lv<1> > xor_ln68_1_fu_563_p2;
    sc_signal< sc_lv<16> > zext_ln700_fu_569_p1;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<16> ap_const_lv16_FF70;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_accum_V_1_fu_573_p2();
    void thread_accum_V_fu_332_p2();
    void thread_add_ln68_1_fu_387_p2();
    void thread_add_ln68_2_fu_425_p2();
    void thread_add_ln68_3_fu_452_p2();
    void thread_add_ln68_4_fu_543_p2();
    void thread_add_ln68_5_fu_489_p2();
    void thread_add_ln68_6_fu_495_p2();
    void thread_add_ln68_7_fu_520_p2();
    void thread_add_ln68_8_fu_526_p2();
    void thread_add_ln68_fu_312_p2();
    void thread_add_ln73_1_fu_361_p2();
    void thread_add_ln73_fu_348_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_fu_306_p2();
    void thread_icmp_ln61_fu_231_p2();
    void thread_icmp_ln62_fu_268_p2();
    void thread_icmp_ln63_fu_284_p2();
    void thread_icmp_ln65_fu_300_p2();
    void thread_icmp_ln66_fu_375_p2();
    void thread_icmp_ln67_fu_401_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_m_fu_407_p2();
    void thread_n_fu_237_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p_shl4_cast_fu_531_p3();
    void thread_p_shl_cast_fu_500_p3();
    void thread_r_fu_381_p2();
    void thread_sext_ln62_fu_264_p1();
    void thread_shl_ln1503_fu_326_p2();
    void thread_sub_ln68_1_fu_538_p2();
    void thread_sub_ln68_fu_446_p2();
    void thread_threshold_conv2_V_address0();
    void thread_threshold_conv2_V_ce0();
    void thread_tmp_1_fu_465_p3();
    void thread_tmp_25_cast_fu_353_p3();
    void thread_tmp_2_fu_477_p3();
    void thread_tmp_3_fu_434_p3();
    void thread_tmp_4_fu_508_p3();
    void thread_tmp_fu_252_p3();
    void thread_tmp_s_fu_413_p3();
    void thread_trunc_ln68_1_fu_461_p1();
    void thread_trunc_ln68_fu_457_p1();
    void thread_w_conv2_address0();
    void thread_w_conv2_ce0();
    void thread_x_fu_274_p2();
    void thread_xor_ln68_1_fu_563_p2();
    void thread_xor_ln68_fu_557_p2();
    void thread_y_fu_290_p2();
    void thread_zext_ln63_fu_280_p1();
    void thread_zext_ln65_fu_296_p1();
    void thread_zext_ln66_1_fu_322_p1();
    void thread_zext_ln66_fu_371_p1();
    void thread_zext_ln68_10_fu_516_p1();
    void thread_zext_ln68_11_fu_553_p1();
    void thread_zext_ln68_1_fu_318_p1();
    void thread_zext_ln68_2_fu_393_p1();
    void thread_zext_ln68_3_fu_397_p1();
    void thread_zext_ln68_4_fu_421_p1();
    void thread_zext_ln68_5_fu_430_p1();
    void thread_zext_ln68_6_fu_442_p1();
    void thread_zext_ln68_7_fu_548_p1();
    void thread_zext_ln68_8_fu_473_p1();
    void thread_zext_ln68_9_fu_485_p1();
    void thread_zext_ln68_fu_243_p1();
    void thread_zext_ln700_fu_569_p1();
    void thread_zext_ln73_1_fu_344_p1();
    void thread_zext_ln73_2_fu_366_p1();
    void thread_zext_ln73_fu_248_p1();
    void thread_zext_ln895_fu_260_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
