// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_16_32_10_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_16_32_10_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_16_32_10_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state1 = "1";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state2 = "10";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state3 = "100";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state4 = "1000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state5 = "10000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state6 = "100000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> conv_16_32_10_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_1 = "1";
const sc_lv<1> conv_16_32_10_s::ap_const_lv1_0 = "0";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_2 = "10";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_3 = "11";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_4 = "100";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_5 = "101";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_6 = "110";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_7 = "111";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_8 = "1000";
const sc_lv<32> conv_16_32_10_s::ap_const_lv32_9 = "1001";
const sc_lv<6> conv_16_32_10_s::ap_const_lv6_0 = "000000";
const sc_lv<1> conv_16_32_10_s::ap_const_lv1_1 = "1";
const sc_lv<4> conv_16_32_10_s::ap_const_lv4_0 = "0000";
const sc_lv<16> conv_16_32_10_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> conv_16_32_10_s::ap_const_lv2_0 = "00";
const sc_lv<5> conv_16_32_10_s::ap_const_lv5_0 = "00000";
const sc_lv<6> conv_16_32_10_s::ap_const_lv6_20 = "100000";
const sc_lv<6> conv_16_32_10_s::ap_const_lv6_1 = "1";
const sc_lv<3> conv_16_32_10_s::ap_const_lv3_0 = "000";
const sc_lv<4> conv_16_32_10_s::ap_const_lv4_8 = "1000";
const sc_lv<4> conv_16_32_10_s::ap_const_lv4_1 = "1";
const sc_lv<2> conv_16_32_10_s::ap_const_lv2_3 = "11";
const sc_lv<2> conv_16_32_10_s::ap_const_lv2_1 = "1";
const sc_lv<16> conv_16_32_10_s::ap_const_lv16_1 = "1";
const sc_lv<16> conv_16_32_10_s::ap_const_lv16_FF70 = "1111111101110000";
const sc_lv<5> conv_16_32_10_s::ap_const_lv5_10 = "10000";
const sc_lv<5> conv_16_32_10_s::ap_const_lv5_1 = "1";
const bool conv_16_32_10_s::ap_const_boolean_1 = true;

conv_16_32_10_s::conv_16_32_10_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    threshold_conv2_V_U = new conv_16_32_10_s_tdEe("threshold_conv2_V_U");
    threshold_conv2_V_U->clk(ap_clk);
    threshold_conv2_V_U->reset(ap_rst);
    threshold_conv2_V_U->address0(threshold_conv2_V_address0);
    threshold_conv2_V_U->ce0(threshold_conv2_V_ce0);
    threshold_conv2_V_U->q0(threshold_conv2_V_q0);
    w_conv2_U = new conv_16_32_10_s_weOg("w_conv2_U");
    w_conv2_U->clk(ap_clk);
    w_conv2_U->reset(ap_rst);
    w_conv2_U->address0(w_conv2_address0);
    w_conv2_U->ce0(w_conv2_ce0);
    w_conv2_U->q0(w_conv2_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_accum_V_1_fu_573_p2);
    sensitive << ( p_014_2_reg_208 );
    sensitive << ( zext_ln700_fu_569_p1 );

    SC_METHOD(thread_accum_V_fu_332_p2);
    sensitive << ( shl_ln1503_fu_326_p2 );

    SC_METHOD(thread_add_ln68_1_fu_387_p2);
    sensitive << ( y_0_reg_150 );
    sensitive << ( zext_ln66_fu_371_p1 );

    SC_METHOD(thread_add_ln68_2_fu_425_p2);
    sensitive << ( zext_ln73_reg_592 );
    sensitive << ( zext_ln68_4_fu_421_p1 );

    SC_METHOD(thread_add_ln68_3_fu_452_p2);
    sensitive << ( zext_ln68_3_reg_659 );
    sensitive << ( sub_ln68_fu_446_p2 );

    SC_METHOD(thread_add_ln68_4_fu_543_p2);
    sensitive << ( zext_ln66_1_reg_641 );
    sensitive << ( sub_ln68_1_fu_538_p2 );

    SC_METHOD(thread_add_ln68_5_fu_489_p2);
    sensitive << ( zext_ln68_9_fu_485_p1 );
    sensitive << ( zext_ln68_8_fu_473_p1 );

    SC_METHOD(thread_add_ln68_6_fu_495_p2);
    sensitive << ( zext_ln68_2_reg_654 );
    sensitive << ( add_ln68_5_fu_489_p2 );

    SC_METHOD(thread_add_ln68_7_fu_520_p2);
    sensitive << ( zext_ln68_10_fu_516_p1 );
    sensitive << ( p_shl_cast_fu_500_p3 );

    SC_METHOD(thread_add_ln68_8_fu_526_p2);
    sensitive << ( zext_ln68_1_reg_636 );
    sensitive << ( add_ln68_7_fu_520_p2 );

    SC_METHOD(thread_add_ln68_fu_312_p2);
    sensitive << ( x_0_reg_138 );
    sensitive << ( zext_ln65_fu_296_p1 );

    SC_METHOD(thread_add_ln73_1_fu_361_p2);
    sensitive << ( zext_ln63_reg_615 );
    sensitive << ( tmp_25_cast_fu_353_p3 );

    SC_METHOD(thread_add_ln73_fu_348_p2);
    sensitive << ( zext_ln895_reg_597 );
    sensitive << ( zext_ln73_1_fu_344_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_231_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_231_p2 );

    SC_METHOD(thread_c_fu_306_p2);
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_icmp_ln61_fu_231_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( n_0_reg_126 );

    SC_METHOD(thread_icmp_ln62_fu_268_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_icmp_ln63_fu_284_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_icmp_ln65_fu_300_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_icmp_ln66_fu_375_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_icmp_ln67_fu_401_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( m_0_reg_220 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln68_11_fu_553_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_m_fu_407_p2);
    sensitive << ( m_0_reg_220 );

    SC_METHOD(thread_n_fu_237_p2);
    sensitive << ( n_0_reg_126 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln73_2_fu_366_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( sext_ln62_reg_602 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( accum_V_fu_332_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln65_fu_300_p2 );

    SC_METHOD(thread_p_shl4_cast_fu_531_p3);
    sensitive << ( trunc_ln68_1_reg_677 );

    SC_METHOD(thread_p_shl_cast_fu_500_p3);
    sensitive << ( add_ln68_6_fu_495_p2 );

    SC_METHOD(thread_r_fu_381_p2);
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_sext_ln62_fu_264_p1);
    sensitive << ( threshold_conv2_V_q0 );

    SC_METHOD(thread_shl_ln1503_fu_326_p2);
    sensitive << ( p_014_0_reg_162 );

    SC_METHOD(thread_sub_ln68_1_fu_538_p2);
    sensitive << ( trunc_ln68_reg_672 );
    sensitive << ( p_shl4_cast_fu_531_p3 );

    SC_METHOD(thread_sub_ln68_fu_446_p2);
    sensitive << ( zext_ln68_6_fu_442_p1 );
    sensitive << ( zext_ln68_5_fu_430_p1 );

    SC_METHOD(thread_threshold_conv2_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln68_fu_243_p1 );

    SC_METHOD(thread_threshold_conv2_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_1_fu_465_p3);
    sensitive << ( m_0_reg_220 );

    SC_METHOD(thread_tmp_25_cast_fu_353_p3);
    sensitive << ( add_ln73_fu_348_p2 );

    SC_METHOD(thread_tmp_2_fu_477_p3);
    sensitive << ( m_0_reg_220 );

    SC_METHOD(thread_tmp_3_fu_434_p3);
    sensitive << ( add_ln68_2_fu_425_p2 );

    SC_METHOD(thread_tmp_4_fu_508_p3);
    sensitive << ( add_ln68_6_fu_495_p2 );

    SC_METHOD(thread_tmp_fu_252_p3);
    sensitive << ( n_0_reg_126 );

    SC_METHOD(thread_tmp_s_fu_413_p3);
    sensitive << ( m_0_reg_220 );

    SC_METHOD(thread_trunc_ln68_1_fu_461_p1);
    sensitive << ( add_ln68_3_fu_452_p2 );

    SC_METHOD(thread_trunc_ln68_fu_457_p1);
    sensitive << ( add_ln68_3_fu_452_p2 );

    SC_METHOD(thread_w_conv2_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln68_7_fu_548_p1 );

    SC_METHOD(thread_w_conv2_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_x_fu_274_p2);
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_xor_ln68_1_fu_563_p2);
    sensitive << ( input_r_q0 );
    sensitive << ( xor_ln68_fu_557_p2 );

    SC_METHOD(thread_xor_ln68_fu_557_p2);
    sensitive << ( w_conv2_q0 );

    SC_METHOD(thread_y_fu_290_p2);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_zext_ln63_fu_280_p1);
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_zext_ln65_fu_296_p1);
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_zext_ln66_1_fu_322_p1);
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_zext_ln66_fu_371_p1);
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_zext_ln68_10_fu_516_p1);
    sensitive << ( tmp_4_fu_508_p3 );

    SC_METHOD(thread_zext_ln68_11_fu_553_p1);
    sensitive << ( add_ln68_8_reg_682 );

    SC_METHOD(thread_zext_ln68_1_fu_318_p1);
    sensitive << ( add_ln68_fu_312_p2 );

    SC_METHOD(thread_zext_ln68_2_fu_393_p1);
    sensitive << ( add_ln68_1_fu_387_p2 );

    SC_METHOD(thread_zext_ln68_3_fu_397_p1);
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_zext_ln68_4_fu_421_p1);
    sensitive << ( tmp_s_fu_413_p3 );

    SC_METHOD(thread_zext_ln68_5_fu_430_p1);
    sensitive << ( add_ln68_2_fu_425_p2 );

    SC_METHOD(thread_zext_ln68_6_fu_442_p1);
    sensitive << ( tmp_3_fu_434_p3 );

    SC_METHOD(thread_zext_ln68_7_fu_548_p1);
    sensitive << ( add_ln68_4_fu_543_p2 );

    SC_METHOD(thread_zext_ln68_8_fu_473_p1);
    sensitive << ( tmp_1_fu_465_p3 );

    SC_METHOD(thread_zext_ln68_9_fu_485_p1);
    sensitive << ( tmp_2_fu_477_p3 );

    SC_METHOD(thread_zext_ln68_fu_243_p1);
    sensitive << ( n_0_reg_126 );

    SC_METHOD(thread_zext_ln700_fu_569_p1);
    sensitive << ( xor_ln68_1_fu_563_p2 );

    SC_METHOD(thread_zext_ln73_1_fu_344_p1);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_zext_ln73_2_fu_366_p1);
    sensitive << ( add_ln73_1_fu_361_p2 );

    SC_METHOD(thread_zext_ln73_fu_248_p1);
    sensitive << ( n_0_reg_126 );

    SC_METHOD(thread_zext_ln895_fu_260_p1);
    sensitive << ( tmp_fu_252_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_231_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln62_fu_268_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln65_fu_300_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln66_fu_375_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln67_fu_401_p2 );
    sensitive << ( icmp_ln63_fu_284_p2 );

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_16_32_10_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, threshold_conv2_V_address0, "threshold_conv2_V_address0");
    sc_trace(mVcdFile, threshold_conv2_V_ce0, "threshold_conv2_V_ce0");
    sc_trace(mVcdFile, threshold_conv2_V_q0, "threshold_conv2_V_q0");
    sc_trace(mVcdFile, w_conv2_address0, "w_conv2_address0");
    sc_trace(mVcdFile, w_conv2_ce0, "w_conv2_ce0");
    sc_trace(mVcdFile, w_conv2_q0, "w_conv2_q0");
    sc_trace(mVcdFile, n_fu_237_p2, "n_fu_237_p2");
    sc_trace(mVcdFile, n_reg_582, "n_reg_582");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln61_fu_231_p2, "icmp_ln61_fu_231_p2");
    sc_trace(mVcdFile, zext_ln73_fu_248_p1, "zext_ln73_fu_248_p1");
    sc_trace(mVcdFile, zext_ln73_reg_592, "zext_ln73_reg_592");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln895_fu_260_p1, "zext_ln895_fu_260_p1");
    sc_trace(mVcdFile, zext_ln895_reg_597, "zext_ln895_reg_597");
    sc_trace(mVcdFile, sext_ln62_fu_264_p1, "sext_ln62_fu_264_p1");
    sc_trace(mVcdFile, sext_ln62_reg_602, "sext_ln62_reg_602");
    sc_trace(mVcdFile, x_fu_274_p2, "x_fu_274_p2");
    sc_trace(mVcdFile, x_reg_610, "x_reg_610");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln63_fu_280_p1, "zext_ln63_fu_280_p1");
    sc_trace(mVcdFile, zext_ln63_reg_615, "zext_ln63_reg_615");
    sc_trace(mVcdFile, icmp_ln62_fu_268_p2, "icmp_ln62_fu_268_p2");
    sc_trace(mVcdFile, y_fu_290_p2, "y_fu_290_p2");
    sc_trace(mVcdFile, y_reg_623, "y_reg_623");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, c_fu_306_p2, "c_fu_306_p2");
    sc_trace(mVcdFile, c_reg_631, "c_reg_631");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln68_1_fu_318_p1, "zext_ln68_1_fu_318_p1");
    sc_trace(mVcdFile, zext_ln68_1_reg_636, "zext_ln68_1_reg_636");
    sc_trace(mVcdFile, icmp_ln65_fu_300_p2, "icmp_ln65_fu_300_p2");
    sc_trace(mVcdFile, zext_ln66_1_fu_322_p1, "zext_ln66_1_fu_322_p1");
    sc_trace(mVcdFile, zext_ln66_1_reg_641, "zext_ln66_1_reg_641");
    sc_trace(mVcdFile, r_fu_381_p2, "r_fu_381_p2");
    sc_trace(mVcdFile, r_reg_649, "r_reg_649");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln68_2_fu_393_p1, "zext_ln68_2_fu_393_p1");
    sc_trace(mVcdFile, zext_ln68_2_reg_654, "zext_ln68_2_reg_654");
    sc_trace(mVcdFile, icmp_ln66_fu_375_p2, "icmp_ln66_fu_375_p2");
    sc_trace(mVcdFile, zext_ln68_3_fu_397_p1, "zext_ln68_3_fu_397_p1");
    sc_trace(mVcdFile, zext_ln68_3_reg_659, "zext_ln68_3_reg_659");
    sc_trace(mVcdFile, m_fu_407_p2, "m_fu_407_p2");
    sc_trace(mVcdFile, m_reg_667, "m_reg_667");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, trunc_ln68_fu_457_p1, "trunc_ln68_fu_457_p1");
    sc_trace(mVcdFile, trunc_ln68_reg_672, "trunc_ln68_reg_672");
    sc_trace(mVcdFile, icmp_ln67_fu_401_p2, "icmp_ln67_fu_401_p2");
    sc_trace(mVcdFile, trunc_ln68_1_fu_461_p1, "trunc_ln68_1_fu_461_p1");
    sc_trace(mVcdFile, trunc_ln68_1_reg_677, "trunc_ln68_1_reg_677");
    sc_trace(mVcdFile, add_ln68_8_fu_526_p2, "add_ln68_8_fu_526_p2");
    sc_trace(mVcdFile, add_ln68_8_reg_682, "add_ln68_8_reg_682");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, accum_V_1_fu_573_p2, "accum_V_1_fu_573_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, n_0_reg_126, "n_0_reg_126");
    sc_trace(mVcdFile, x_0_reg_138, "x_0_reg_138");
    sc_trace(mVcdFile, icmp_ln63_fu_284_p2, "icmp_ln63_fu_284_p2");
    sc_trace(mVcdFile, y_0_reg_150, "y_0_reg_150");
    sc_trace(mVcdFile, p_014_0_reg_162, "p_014_0_reg_162");
    sc_trace(mVcdFile, c_0_reg_174, "c_0_reg_174");
    sc_trace(mVcdFile, p_014_1_reg_185, "p_014_1_reg_185");
    sc_trace(mVcdFile, r_0_reg_197, "r_0_reg_197");
    sc_trace(mVcdFile, p_014_2_reg_208, "p_014_2_reg_208");
    sc_trace(mVcdFile, m_0_reg_220, "m_0_reg_220");
    sc_trace(mVcdFile, zext_ln68_fu_243_p1, "zext_ln68_fu_243_p1");
    sc_trace(mVcdFile, zext_ln73_2_fu_366_p1, "zext_ln73_2_fu_366_p1");
    sc_trace(mVcdFile, zext_ln68_7_fu_548_p1, "zext_ln68_7_fu_548_p1");
    sc_trace(mVcdFile, zext_ln68_11_fu_553_p1, "zext_ln68_11_fu_553_p1");
    sc_trace(mVcdFile, tmp_fu_252_p3, "tmp_fu_252_p3");
    sc_trace(mVcdFile, zext_ln65_fu_296_p1, "zext_ln65_fu_296_p1");
    sc_trace(mVcdFile, add_ln68_fu_312_p2, "add_ln68_fu_312_p2");
    sc_trace(mVcdFile, shl_ln1503_fu_326_p2, "shl_ln1503_fu_326_p2");
    sc_trace(mVcdFile, accum_V_fu_332_p2, "accum_V_fu_332_p2");
    sc_trace(mVcdFile, zext_ln73_1_fu_344_p1, "zext_ln73_1_fu_344_p1");
    sc_trace(mVcdFile, add_ln73_fu_348_p2, "add_ln73_fu_348_p2");
    sc_trace(mVcdFile, tmp_25_cast_fu_353_p3, "tmp_25_cast_fu_353_p3");
    sc_trace(mVcdFile, add_ln73_1_fu_361_p2, "add_ln73_1_fu_361_p2");
    sc_trace(mVcdFile, zext_ln66_fu_371_p1, "zext_ln66_fu_371_p1");
    sc_trace(mVcdFile, add_ln68_1_fu_387_p2, "add_ln68_1_fu_387_p2");
    sc_trace(mVcdFile, tmp_s_fu_413_p3, "tmp_s_fu_413_p3");
    sc_trace(mVcdFile, zext_ln68_4_fu_421_p1, "zext_ln68_4_fu_421_p1");
    sc_trace(mVcdFile, add_ln68_2_fu_425_p2, "add_ln68_2_fu_425_p2");
    sc_trace(mVcdFile, tmp_3_fu_434_p3, "tmp_3_fu_434_p3");
    sc_trace(mVcdFile, zext_ln68_6_fu_442_p1, "zext_ln68_6_fu_442_p1");
    sc_trace(mVcdFile, zext_ln68_5_fu_430_p1, "zext_ln68_5_fu_430_p1");
    sc_trace(mVcdFile, sub_ln68_fu_446_p2, "sub_ln68_fu_446_p2");
    sc_trace(mVcdFile, add_ln68_3_fu_452_p2, "add_ln68_3_fu_452_p2");
    sc_trace(mVcdFile, tmp_1_fu_465_p3, "tmp_1_fu_465_p3");
    sc_trace(mVcdFile, tmp_2_fu_477_p3, "tmp_2_fu_477_p3");
    sc_trace(mVcdFile, zext_ln68_9_fu_485_p1, "zext_ln68_9_fu_485_p1");
    sc_trace(mVcdFile, zext_ln68_8_fu_473_p1, "zext_ln68_8_fu_473_p1");
    sc_trace(mVcdFile, add_ln68_5_fu_489_p2, "add_ln68_5_fu_489_p2");
    sc_trace(mVcdFile, add_ln68_6_fu_495_p2, "add_ln68_6_fu_495_p2");
    sc_trace(mVcdFile, tmp_4_fu_508_p3, "tmp_4_fu_508_p3");
    sc_trace(mVcdFile, zext_ln68_10_fu_516_p1, "zext_ln68_10_fu_516_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_500_p3, "p_shl_cast_fu_500_p3");
    sc_trace(mVcdFile, add_ln68_7_fu_520_p2, "add_ln68_7_fu_520_p2");
    sc_trace(mVcdFile, p_shl4_cast_fu_531_p3, "p_shl4_cast_fu_531_p3");
    sc_trace(mVcdFile, sub_ln68_1_fu_538_p2, "sub_ln68_1_fu_538_p2");
    sc_trace(mVcdFile, add_ln68_4_fu_543_p2, "add_ln68_4_fu_543_p2");
    sc_trace(mVcdFile, xor_ln68_fu_557_p2, "xor_ln68_fu_557_p2");
    sc_trace(mVcdFile, xor_ln68_1_fu_563_p2, "xor_ln68_1_fu_563_p2");
    sc_trace(mVcdFile, zext_ln700_fu_569_p1, "zext_ln700_fu_569_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv_16_32_10_s::~conv_16_32_10_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete threshold_conv2_V_U;
    delete w_conv2_U;
}

void conv_16_32_10_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_284_p2.read()))) {
        c_0_reg_174 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_375_p2.read(), ap_const_lv1_1))) {
        c_0_reg_174 = c_reg_631.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_375_p2.read()))) {
        m_0_reg_220 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        m_0_reg_220 = m_reg_667.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln62_fu_268_p2.read(), ap_const_lv1_1))) {
        n_0_reg_126 = n_reg_582.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n_0_reg_126 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_284_p2.read()))) {
        p_014_0_reg_162 = ap_const_lv16_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_375_p2.read(), ap_const_lv1_1))) {
        p_014_0_reg_162 = p_014_1_reg_185.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln67_fu_401_p2.read(), ap_const_lv1_1))) {
        p_014_1_reg_185 = p_014_2_reg_208.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_300_p2.read()))) {
        p_014_1_reg_185 = p_014_0_reg_162.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_375_p2.read()))) {
        p_014_2_reg_208 = p_014_1_reg_185.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_014_2_reg_208 = accum_V_1_fu_573_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln67_fu_401_p2.read(), ap_const_lv1_1))) {
        r_0_reg_197 = r_reg_649.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_300_p2.read()))) {
        r_0_reg_197 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_284_p2.read()))) {
        x_0_reg_138 = x_reg_610.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_0_reg_138 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln62_fu_268_p2.read()))) {
        y_0_reg_150 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln65_fu_300_p2.read(), ap_const_lv1_1))) {
        y_0_reg_150 = y_reg_623.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln67_fu_401_p2.read()))) {
        add_ln68_8_reg_682 = add_ln68_8_fu_526_p2.read();
        trunc_ln68_1_reg_677 = trunc_ln68_1_fu_461_p1.read();
        trunc_ln68_reg_672 = trunc_ln68_fu_457_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c_reg_631 = c_fu_306_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        m_reg_667 = m_fu_407_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        n_reg_582 = n_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_reg_649 = r_fu_381_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sext_ln62_reg_602 = sext_ln62_fu_264_p1.read();
        zext_ln73_reg_592 = zext_ln73_fu_248_p1.read();
        zext_ln895_reg_597 = zext_ln895_fu_260_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_610 = x_fu_274_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_reg_623 = y_fu_290_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln62_fu_268_p2.read()))) {
        zext_ln63_reg_615 = zext_ln63_fu_280_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_300_p2.read()))) {
        zext_ln66_1_reg_641 = zext_ln66_1_fu_322_p1.read();
        zext_ln68_1_reg_636 = zext_ln68_1_fu_318_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_375_p2.read()))) {
        zext_ln68_2_reg_654 = zext_ln68_2_fu_393_p1.read();
        zext_ln68_3_reg_659 = zext_ln68_3_fu_397_p1.read();
    }
}

void conv_16_32_10_s::thread_accum_V_1_fu_573_p2() {
    accum_V_1_fu_573_p2 = (!p_014_2_reg_208.read().is_01() || !zext_ln700_fu_569_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_014_2_reg_208.read()) + sc_biguint<16>(zext_ln700_fu_569_p1.read()));
}

void conv_16_32_10_s::thread_accum_V_fu_332_p2() {
    accum_V_fu_332_p2 = (!ap_const_lv16_FF70.is_01() || !shl_ln1503_fu_326_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FF70) + sc_biguint<16>(shl_ln1503_fu_326_p2.read()));
}

void conv_16_32_10_s::thread_add_ln68_1_fu_387_p2() {
    add_ln68_1_fu_387_p2 = (!zext_ln66_fu_371_p1.read().is_01() || !y_0_reg_150.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln66_fu_371_p1.read()) + sc_biguint<4>(y_0_reg_150.read()));
}

void conv_16_32_10_s::thread_add_ln68_2_fu_425_p2() {
    add_ln68_2_fu_425_p2 = (!zext_ln68_4_fu_421_p1.read().is_01() || !zext_ln73_reg_592.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln68_4_fu_421_p1.read()) + sc_biguint<11>(zext_ln73_reg_592.read()));
}

void conv_16_32_10_s::thread_add_ln68_3_fu_452_p2() {
    add_ln68_3_fu_452_p2 = (!sub_ln68_fu_446_p2.read().is_01() || !zext_ln68_3_reg_659.read().is_01())? sc_lv<64>(): (sc_biguint<64>(sub_ln68_fu_446_p2.read()) + sc_biguint<64>(zext_ln68_3_reg_659.read()));
}

void conv_16_32_10_s::thread_add_ln68_4_fu_543_p2() {
    add_ln68_4_fu_543_p2 = (!sub_ln68_1_fu_538_p2.read().is_01() || !zext_ln66_1_reg_641.read().is_01())? sc_lv<14>(): (sc_biguint<14>(sub_ln68_1_fu_538_p2.read()) + sc_biguint<14>(zext_ln66_1_reg_641.read()));
}

void conv_16_32_10_s::thread_add_ln68_5_fu_489_p2() {
    add_ln68_5_fu_489_p2 = (!zext_ln68_9_fu_485_p1.read().is_01() || !zext_ln68_8_fu_473_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln68_9_fu_485_p1.read()) + sc_biguint<9>(zext_ln68_8_fu_473_p1.read()));
}

void conv_16_32_10_s::thread_add_ln68_6_fu_495_p2() {
    add_ln68_6_fu_495_p2 = (!add_ln68_5_fu_489_p2.read().is_01() || !zext_ln68_2_reg_654.read().is_01())? sc_lv<9>(): (sc_biguint<9>(add_ln68_5_fu_489_p2.read()) + sc_biguint<9>(zext_ln68_2_reg_654.read()));
}

void conv_16_32_10_s::thread_add_ln68_7_fu_520_p2() {
    add_ln68_7_fu_520_p2 = (!zext_ln68_10_fu_516_p1.read().is_01() || !p_shl_cast_fu_500_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln68_10_fu_516_p1.read()) + sc_biguint<12>(p_shl_cast_fu_500_p3.read()));
}

void conv_16_32_10_s::thread_add_ln68_8_fu_526_p2() {
    add_ln68_8_fu_526_p2 = (!add_ln68_7_fu_520_p2.read().is_01() || !zext_ln68_1_reg_636.read().is_01())? sc_lv<12>(): (sc_biguint<12>(add_ln68_7_fu_520_p2.read()) + sc_biguint<12>(zext_ln68_1_reg_636.read()));
}

void conv_16_32_10_s::thread_add_ln68_fu_312_p2() {
    add_ln68_fu_312_p2 = (!zext_ln65_fu_296_p1.read().is_01() || !x_0_reg_138.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln65_fu_296_p1.read()) + sc_biguint<4>(x_0_reg_138.read()));
}

void conv_16_32_10_s::thread_add_ln73_1_fu_361_p2() {
    add_ln73_1_fu_361_p2 = (!tmp_25_cast_fu_353_p3.read().is_01() || !zext_ln63_reg_615.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_25_cast_fu_353_p3.read()) + sc_biguint<13>(zext_ln63_reg_615.read()));
}

void conv_16_32_10_s::thread_add_ln73_fu_348_p2() {
    add_ln73_fu_348_p2 = (!zext_ln895_reg_597.read().is_01() || !zext_ln73_1_fu_344_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln895_reg_597.read()) + sc_biguint<10>(zext_ln73_1_fu_344_p1.read()));
}

void conv_16_32_10_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_16_32_10_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_16_32_10_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln61_fu_231_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln61_fu_231_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_c_fu_306_p2() {
    c_fu_306_p2 = (!c_0_reg_174.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_174.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_16_32_10_s::thread_icmp_ln61_fu_231_p2() {
    icmp_ln61_fu_231_p2 = (!n_0_reg_126.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(n_0_reg_126.read() == ap_const_lv6_20);
}

void conv_16_32_10_s::thread_icmp_ln62_fu_268_p2() {
    icmp_ln62_fu_268_p2 = (!x_0_reg_138.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_138.read() == ap_const_lv4_8);
}

void conv_16_32_10_s::thread_icmp_ln63_fu_284_p2() {
    icmp_ln63_fu_284_p2 = (!y_0_reg_150.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_150.read() == ap_const_lv4_8);
}

void conv_16_32_10_s::thread_icmp_ln65_fu_300_p2() {
    icmp_ln65_fu_300_p2 = (!c_0_reg_174.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_174.read() == ap_const_lv2_3);
}

void conv_16_32_10_s::thread_icmp_ln66_fu_375_p2() {
    icmp_ln66_fu_375_p2 = (!r_0_reg_197.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_197.read() == ap_const_lv2_3);
}

void conv_16_32_10_s::thread_icmp_ln67_fu_401_p2() {
    icmp_ln67_fu_401_p2 = (!m_0_reg_220.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_220.read() == ap_const_lv5_10);
}

void conv_16_32_10_s::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<11>) (zext_ln68_11_fu_553_p1.read());
}

void conv_16_32_10_s::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_m_fu_407_p2() {
    m_fu_407_p2 = (!m_0_reg_220.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_0_reg_220.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_16_32_10_s::thread_n_fu_237_p2() {
    n_fu_237_p2 = (!n_0_reg_126.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(n_0_reg_126.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_16_32_10_s::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<11>) (zext_ln73_2_fu_366_p1.read());
}

void conv_16_32_10_s::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_output_r_d0() {
    output_r_d0 = (!accum_V_fu_332_p2.read().is_01() || !sext_ln62_reg_602.read().is_01())? sc_lv<1>(): (sc_bigint<16>(accum_V_fu_332_p2.read()) > sc_bigint<16>(sext_ln62_reg_602.read()));
}

void conv_16_32_10_s::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_300_p2.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_p_shl4_cast_fu_531_p3() {
    p_shl4_cast_fu_531_p3 = esl_concat<12,2>(trunc_ln68_1_reg_677.read(), ap_const_lv2_0);
}

void conv_16_32_10_s::thread_p_shl_cast_fu_500_p3() {
    p_shl_cast_fu_500_p3 = esl_concat<9,3>(add_ln68_6_fu_495_p2.read(), ap_const_lv3_0);
}

void conv_16_32_10_s::thread_r_fu_381_p2() {
    r_fu_381_p2 = (!r_0_reg_197.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_197.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_16_32_10_s::thread_sext_ln62_fu_264_p1() {
    sext_ln62_fu_264_p1 = esl_sext<16,5>(threshold_conv2_V_q0.read());
}

void conv_16_32_10_s::thread_shl_ln1503_fu_326_p2() {
    shl_ln1503_fu_326_p2 = (!ap_const_lv16_1.is_01())? sc_lv<16>(): p_014_0_reg_162.read() << (unsigned short)ap_const_lv16_1.to_uint();
}

void conv_16_32_10_s::thread_sub_ln68_1_fu_538_p2() {
    sub_ln68_1_fu_538_p2 = (!p_shl4_cast_fu_531_p3.read().is_01() || !trunc_ln68_reg_672.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl4_cast_fu_531_p3.read()) - sc_biguint<14>(trunc_ln68_reg_672.read()));
}

void conv_16_32_10_s::thread_sub_ln68_fu_446_p2() {
    sub_ln68_fu_446_p2 = (!zext_ln68_6_fu_442_p1.read().is_01() || !zext_ln68_5_fu_430_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln68_6_fu_442_p1.read()) - sc_biguint<64>(zext_ln68_5_fu_430_p1.read()));
}

void conv_16_32_10_s::thread_threshold_conv2_V_address0() {
    threshold_conv2_V_address0 =  (sc_lv<5>) (zext_ln68_fu_243_p1.read());
}

void conv_16_32_10_s::thread_threshold_conv2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        threshold_conv2_V_ce0 = ap_const_logic_1;
    } else {
        threshold_conv2_V_ce0 = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_tmp_1_fu_465_p3() {
    tmp_1_fu_465_p3 = esl_concat<5,3>(m_0_reg_220.read(), ap_const_lv3_0);
}

void conv_16_32_10_s::thread_tmp_25_cast_fu_353_p3() {
    tmp_25_cast_fu_353_p3 = esl_concat<10,3>(add_ln73_fu_348_p2.read(), ap_const_lv3_0);
}

void conv_16_32_10_s::thread_tmp_2_fu_477_p3() {
    tmp_2_fu_477_p3 = esl_concat<5,1>(m_0_reg_220.read(), ap_const_lv1_0);
}

void conv_16_32_10_s::thread_tmp_3_fu_434_p3() {
    tmp_3_fu_434_p3 = esl_concat<11,2>(add_ln68_2_fu_425_p2.read(), ap_const_lv2_0);
}

void conv_16_32_10_s::thread_tmp_4_fu_508_p3() {
    tmp_4_fu_508_p3 = esl_concat<9,1>(add_ln68_6_fu_495_p2.read(), ap_const_lv1_0);
}

void conv_16_32_10_s::thread_tmp_fu_252_p3() {
    tmp_fu_252_p3 = esl_concat<6,3>(n_0_reg_126.read(), ap_const_lv3_0);
}

void conv_16_32_10_s::thread_tmp_s_fu_413_p3() {
    tmp_s_fu_413_p3 = esl_concat<5,5>(m_0_reg_220.read(), ap_const_lv5_0);
}

void conv_16_32_10_s::thread_trunc_ln68_1_fu_461_p1() {
    trunc_ln68_1_fu_461_p1 = add_ln68_3_fu_452_p2.read().range(12-1, 0);
}

void conv_16_32_10_s::thread_trunc_ln68_fu_457_p1() {
    trunc_ln68_fu_457_p1 = add_ln68_3_fu_452_p2.read().range(14-1, 0);
}

void conv_16_32_10_s::thread_w_conv2_address0() {
    w_conv2_address0 =  (sc_lv<13>) (zext_ln68_7_fu_548_p1.read());
}

void conv_16_32_10_s::thread_w_conv2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        w_conv2_ce0 = ap_const_logic_1;
    } else {
        w_conv2_ce0 = ap_const_logic_0;
    }
}

void conv_16_32_10_s::thread_x_fu_274_p2() {
    x_fu_274_p2 = (!x_0_reg_138.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(x_0_reg_138.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_16_32_10_s::thread_xor_ln68_1_fu_563_p2() {
    xor_ln68_1_fu_563_p2 = (input_r_q0.read() ^ xor_ln68_fu_557_p2.read());
}

void conv_16_32_10_s::thread_xor_ln68_fu_557_p2() {
    xor_ln68_fu_557_p2 = (w_conv2_q0.read() ^ ap_const_lv1_1);
}

void conv_16_32_10_s::thread_y_fu_290_p2() {
    y_fu_290_p2 = (!y_0_reg_150.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(y_0_reg_150.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_16_32_10_s::thread_zext_ln63_fu_280_p1() {
    zext_ln63_fu_280_p1 = esl_zext<13,4>(x_0_reg_138.read());
}

void conv_16_32_10_s::thread_zext_ln65_fu_296_p1() {
    zext_ln65_fu_296_p1 = esl_zext<4,2>(c_0_reg_174.read());
}

void conv_16_32_10_s::thread_zext_ln66_1_fu_322_p1() {
    zext_ln66_1_fu_322_p1 = esl_zext<14,2>(c_0_reg_174.read());
}

void conv_16_32_10_s::thread_zext_ln66_fu_371_p1() {
    zext_ln66_fu_371_p1 = esl_zext<4,2>(r_0_reg_197.read());
}

void conv_16_32_10_s::thread_zext_ln68_10_fu_516_p1() {
    zext_ln68_10_fu_516_p1 = esl_zext<12,10>(tmp_4_fu_508_p3.read());
}

void conv_16_32_10_s::thread_zext_ln68_11_fu_553_p1() {
    zext_ln68_11_fu_553_p1 = esl_zext<64,12>(add_ln68_8_reg_682.read());
}

void conv_16_32_10_s::thread_zext_ln68_1_fu_318_p1() {
    zext_ln68_1_fu_318_p1 = esl_zext<12,4>(add_ln68_fu_312_p2.read());
}

void conv_16_32_10_s::thread_zext_ln68_2_fu_393_p1() {
    zext_ln68_2_fu_393_p1 = esl_zext<9,4>(add_ln68_1_fu_387_p2.read());
}

void conv_16_32_10_s::thread_zext_ln68_3_fu_397_p1() {
    zext_ln68_3_fu_397_p1 = esl_zext<64,2>(r_0_reg_197.read());
}

void conv_16_32_10_s::thread_zext_ln68_4_fu_421_p1() {
    zext_ln68_4_fu_421_p1 = esl_zext<11,10>(tmp_s_fu_413_p3.read());
}

void conv_16_32_10_s::thread_zext_ln68_5_fu_430_p1() {
    zext_ln68_5_fu_430_p1 = esl_zext<64,11>(add_ln68_2_fu_425_p2.read());
}

void conv_16_32_10_s::thread_zext_ln68_6_fu_442_p1() {
    zext_ln68_6_fu_442_p1 = esl_zext<64,13>(tmp_3_fu_434_p3.read());
}

void conv_16_32_10_s::thread_zext_ln68_7_fu_548_p1() {
    zext_ln68_7_fu_548_p1 = esl_zext<64,14>(add_ln68_4_fu_543_p2.read());
}

void conv_16_32_10_s::thread_zext_ln68_8_fu_473_p1() {
    zext_ln68_8_fu_473_p1 = esl_zext<9,8>(tmp_1_fu_465_p3.read());
}

void conv_16_32_10_s::thread_zext_ln68_9_fu_485_p1() {
    zext_ln68_9_fu_485_p1 = esl_zext<9,6>(tmp_2_fu_477_p3.read());
}

void conv_16_32_10_s::thread_zext_ln68_fu_243_p1() {
    zext_ln68_fu_243_p1 = esl_zext<64,6>(n_0_reg_126.read());
}

void conv_16_32_10_s::thread_zext_ln700_fu_569_p1() {
    zext_ln700_fu_569_p1 = esl_zext<16,1>(xor_ln68_1_fu_563_p2.read());
}

void conv_16_32_10_s::thread_zext_ln73_1_fu_344_p1() {
    zext_ln73_1_fu_344_p1 = esl_zext<10,4>(y_0_reg_150.read());
}

void conv_16_32_10_s::thread_zext_ln73_2_fu_366_p1() {
    zext_ln73_2_fu_366_p1 = esl_zext<64,13>(add_ln73_1_fu_361_p2.read());
}

void conv_16_32_10_s::thread_zext_ln73_fu_248_p1() {
    zext_ln73_fu_248_p1 = esl_zext<11,6>(n_0_reg_126.read());
}

void conv_16_32_10_s::thread_zext_ln895_fu_260_p1() {
    zext_ln895_fu_260_p1 = esl_zext<10,9>(tmp_fu_252_p3.read());
}

void conv_16_32_10_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln61_fu_231_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln62_fu_268_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_284_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln65_fu_300_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln66_fu_375_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln67_fu_401_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

