// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_1_16_18_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_1_16_18_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_1_16_18_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state1 = "1";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state2 = "10";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state3 = "100";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state4 = "1000";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state5 = "10000";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state6 = "100000";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> conv_1_16_18_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_1 = "1";
const sc_lv<1> conv_1_16_18_s::ap_const_lv1_0 = "0";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_2 = "10";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_3 = "11";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_4 = "100";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_5 = "101";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_6 = "110";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_7 = "111";
const sc_lv<32> conv_1_16_18_s::ap_const_lv32_8 = "1000";
const sc_lv<5> conv_1_16_18_s::ap_const_lv5_0 = "00000";
const sc_lv<1> conv_1_16_18_s::ap_const_lv1_1 = "1";
const sc_lv<16> conv_1_16_18_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> conv_1_16_18_s::ap_const_lv2_0 = "00";
const sc_lv<5> conv_1_16_18_s::ap_const_lv5_10 = "10000";
const sc_lv<5> conv_1_16_18_s::ap_const_lv5_1 = "1";
const sc_lv<4> conv_1_16_18_s::ap_const_lv4_0 = "0000";
const sc_lv<2> conv_1_16_18_s::ap_const_lv2_3 = "11";
const sc_lv<2> conv_1_16_18_s::ap_const_lv2_1 = "1";
const sc_lv<16> conv_1_16_18_s::ap_const_lv16_1 = "1";
const sc_lv<16> conv_1_16_18_s::ap_const_lv16_FFF7 = "1111111111110111";
const sc_lv<9> conv_1_16_18_s::ap_const_lv9_2 = "10";
const bool conv_1_16_18_s::ap_const_boolean_1 = true;

conv_1_16_18_s::conv_1_16_18_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    threshold_conv1_V_U = new conv_1_16_18_s_thbkb("threshold_conv1_V_U");
    threshold_conv1_V_U->clk(ap_clk);
    threshold_conv1_V_U->reset(ap_rst);
    threshold_conv1_V_U->address0(threshold_conv1_V_address0);
    threshold_conv1_V_U->ce0(threshold_conv1_V_ce0);
    threshold_conv1_V_U->q0(threshold_conv1_V_q0);
    w_conv1_0_U = new conv_1_16_18_s_w_cud("w_conv1_0_U");
    w_conv1_0_U->clk(ap_clk);
    w_conv1_0_U->reset(ap_rst);
    w_conv1_0_U->address0(w_conv1_0_address0);
    w_conv1_0_U->ce0(w_conv1_0_ce0);
    w_conv1_0_U->q0(w_conv1_0_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_accum_V_fu_307_p2);
    sensitive << ( shl_ln1503_fu_301_p2 );

    SC_METHOD(thread_add_ln68_10_fu_398_p2);
    sensitive << ( zext_ln68_14_reg_516 );
    sensitive << ( add_ln68_9_fu_392_p2 );

    SC_METHOD(thread_add_ln68_11_fu_412_p2);
    sensitive << ( sext_ln68_reg_472 );
    sensitive << ( zext_ln68_18_fu_408_p1 );

    SC_METHOD(thread_add_ln68_12_fu_429_p2);
    sensitive << ( zext_ln66_2_reg_521 );
    sensitive << ( sub_ln68_2_fu_423_p2 );

    SC_METHOD(thread_add_ln68_2_fu_362_p2);
    sensitive << ( y_0_reg_126 );
    sensitive << ( zext_ln66_fu_346_p1 );

    SC_METHOD(thread_add_ln68_9_fu_392_p2);
    sensitive << ( zext_ln68_15_fu_376_p1 );
    sensitive << ( zext_ln68_16_fu_388_p1 );

    SC_METHOD(thread_add_ln68_fu_287_p2);
    sensitive << ( x_0_reg_114 );
    sensitive << ( zext_ln65_fu_271_p1 );

    SC_METHOD(thread_add_ln700_fu_453_p2);
    sensitive << ( p_014_1_reg_161 );
    sensitive << ( zext_ln700_fu_449_p1 );

    SC_METHOD(thread_add_ln73_2_fu_336_p2);
    sensitive << ( zext_ln63_reg_495 );
    sensitive << ( tmp_36_cast_fu_328_p3 );

    SC_METHOD(thread_add_ln73_fu_323_p2);
    sensitive << ( zext_ln895_reg_477 );
    sensitive << ( zext_ln73_fu_319_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_184_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_184_p2 );

    SC_METHOD(thread_c_fu_281_p2);
    sensitive << ( c_0_reg_150 );

    SC_METHOD(thread_icmp_ln61_fu_184_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_icmp_ln62_fu_243_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_114 );

    SC_METHOD(thread_icmp_ln63_fu_259_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_126 );

    SC_METHOD(thread_icmp_ln65_fu_275_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( c_0_reg_150 );

    SC_METHOD(thread_icmp_ln66_fu_350_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( r_0_reg_173 );

    SC_METHOD(thread_input_0_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln68_17_fu_403_p1 );

    SC_METHOD(thread_input_0_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_n_fu_190_p2);
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln73_3_fu_341_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( sext_ln62_reg_482 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( accum_V_fu_307_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln65_fu_275_p2 );

    SC_METHOD(thread_r_fu_356_p2);
    sensitive << ( r_0_reg_173 );

    SC_METHOD(thread_sext_ln62_fu_239_p1);
    sensitive << ( threshold_conv1_V_q0 );

    SC_METHOD(thread_sext_ln68_fu_223_p1);
    sensitive << ( sub_ln68_fu_217_p2 );

    SC_METHOD(thread_shl_ln1503_fu_301_p2);
    sensitive << ( p_014_0_reg_138 );

    SC_METHOD(thread_shl_ln68_fu_417_p2);
    sensitive << ( add_ln68_11_fu_412_p2 );

    SC_METHOD(thread_sub_ln68_2_fu_423_p2);
    sensitive << ( add_ln68_11_fu_412_p2 );
    sensitive << ( shl_ln68_fu_417_p2 );

    SC_METHOD(thread_sub_ln68_fu_217_p2);
    sensitive << ( zext_ln68_13_fu_213_p1 );
    sensitive << ( zext_ln68_12_fu_201_p1 );

    SC_METHOD(thread_threshold_conv1_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln68_fu_196_p1 );

    SC_METHOD(thread_threshold_conv1_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_36_cast_fu_328_p3);
    sensitive << ( add_ln73_fu_323_p2 );

    SC_METHOD(thread_tmp_3_fu_368_p3);
    sensitive << ( add_ln68_2_fu_362_p2 );

    SC_METHOD(thread_tmp_4_fu_380_p3);
    sensitive << ( add_ln68_2_fu_362_p2 );

    SC_METHOD(thread_tmp_fu_205_p3);
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_tmp_s_fu_227_p3);
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_w_conv1_0_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln68_19_fu_434_p1 );

    SC_METHOD(thread_w_conv1_0_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_x_fu_249_p2);
    sensitive << ( x_0_reg_114 );

    SC_METHOD(thread_xor_ln68_2_fu_444_p2);
    sensitive << ( input_0_load_reg_549 );
    sensitive << ( xor_ln68_fu_438_p2 );

    SC_METHOD(thread_xor_ln68_fu_438_p2);
    sensitive << ( w_conv1_0_q0 );

    SC_METHOD(thread_y_fu_265_p2);
    sensitive << ( y_0_reg_126 );

    SC_METHOD(thread_zext_ln63_fu_255_p1);
    sensitive << ( x_0_reg_114 );

    SC_METHOD(thread_zext_ln65_fu_271_p1);
    sensitive << ( c_0_reg_150 );

    SC_METHOD(thread_zext_ln66_2_fu_297_p1);
    sensitive << ( c_0_reg_150 );

    SC_METHOD(thread_zext_ln66_fu_346_p1);
    sensitive << ( r_0_reg_173 );

    SC_METHOD(thread_zext_ln68_12_fu_201_p1);
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_zext_ln68_13_fu_213_p1);
    sensitive << ( tmp_fu_205_p3 );

    SC_METHOD(thread_zext_ln68_14_fu_293_p1);
    sensitive << ( add_ln68_fu_287_p2 );

    SC_METHOD(thread_zext_ln68_15_fu_376_p1);
    sensitive << ( tmp_3_fu_368_p3 );

    SC_METHOD(thread_zext_ln68_16_fu_388_p1);
    sensitive << ( tmp_4_fu_380_p3 );

    SC_METHOD(thread_zext_ln68_17_fu_403_p1);
    sensitive << ( add_ln68_10_fu_398_p2 );

    SC_METHOD(thread_zext_ln68_18_fu_408_p1);
    sensitive << ( r_0_reg_173 );

    SC_METHOD(thread_zext_ln68_19_fu_434_p1);
    sensitive << ( add_ln68_12_reg_539 );

    SC_METHOD(thread_zext_ln68_fu_196_p1);
    sensitive << ( n_0_reg_102 );

    SC_METHOD(thread_zext_ln700_fu_449_p1);
    sensitive << ( xor_ln68_2_fu_444_p2 );

    SC_METHOD(thread_zext_ln73_3_fu_341_p1);
    sensitive << ( add_ln73_2_fu_336_p2 );

    SC_METHOD(thread_zext_ln73_fu_319_p1);
    sensitive << ( y_0_reg_126 );

    SC_METHOD(thread_zext_ln895_fu_235_p1);
    sensitive << ( tmp_s_fu_227_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_184_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln62_fu_243_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln65_fu_275_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln66_fu_350_p2 );
    sensitive << ( icmp_ln63_fu_259_p2 );

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_1_16_18_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_0_address0, "(port)input_0_address0");
    sc_trace(mVcdFile, input_0_ce0, "(port)input_0_ce0");
    sc_trace(mVcdFile, input_0_q0, "(port)input_0_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, threshold_conv1_V_address0, "threshold_conv1_V_address0");
    sc_trace(mVcdFile, threshold_conv1_V_ce0, "threshold_conv1_V_ce0");
    sc_trace(mVcdFile, threshold_conv1_V_q0, "threshold_conv1_V_q0");
    sc_trace(mVcdFile, w_conv1_0_address0, "w_conv1_0_address0");
    sc_trace(mVcdFile, w_conv1_0_ce0, "w_conv1_0_ce0");
    sc_trace(mVcdFile, w_conv1_0_q0, "w_conv1_0_q0");
    sc_trace(mVcdFile, n_fu_190_p2, "n_fu_190_p2");
    sc_trace(mVcdFile, n_reg_462, "n_reg_462");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln61_fu_184_p2, "icmp_ln61_fu_184_p2");
    sc_trace(mVcdFile, sext_ln68_fu_223_p1, "sext_ln68_fu_223_p1");
    sc_trace(mVcdFile, sext_ln68_reg_472, "sext_ln68_reg_472");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln895_fu_235_p1, "zext_ln895_fu_235_p1");
    sc_trace(mVcdFile, zext_ln895_reg_477, "zext_ln895_reg_477");
    sc_trace(mVcdFile, sext_ln62_fu_239_p1, "sext_ln62_fu_239_p1");
    sc_trace(mVcdFile, sext_ln62_reg_482, "sext_ln62_reg_482");
    sc_trace(mVcdFile, x_fu_249_p2, "x_fu_249_p2");
    sc_trace(mVcdFile, x_reg_490, "x_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln63_fu_255_p1, "zext_ln63_fu_255_p1");
    sc_trace(mVcdFile, zext_ln63_reg_495, "zext_ln63_reg_495");
    sc_trace(mVcdFile, icmp_ln62_fu_243_p2, "icmp_ln62_fu_243_p2");
    sc_trace(mVcdFile, y_fu_265_p2, "y_fu_265_p2");
    sc_trace(mVcdFile, y_reg_503, "y_reg_503");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, c_fu_281_p2, "c_fu_281_p2");
    sc_trace(mVcdFile, c_reg_511, "c_reg_511");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln68_14_fu_293_p1, "zext_ln68_14_fu_293_p1");
    sc_trace(mVcdFile, zext_ln68_14_reg_516, "zext_ln68_14_reg_516");
    sc_trace(mVcdFile, icmp_ln65_fu_275_p2, "icmp_ln65_fu_275_p2");
    sc_trace(mVcdFile, zext_ln66_2_fu_297_p1, "zext_ln66_2_fu_297_p1");
    sc_trace(mVcdFile, zext_ln66_2_reg_521, "zext_ln66_2_reg_521");
    sc_trace(mVcdFile, r_fu_356_p2, "r_fu_356_p2");
    sc_trace(mVcdFile, r_reg_529, "r_reg_529");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln66_fu_350_p2, "icmp_ln66_fu_350_p2");
    sc_trace(mVcdFile, add_ln68_12_fu_429_p2, "add_ln68_12_fu_429_p2");
    sc_trace(mVcdFile, add_ln68_12_reg_539, "add_ln68_12_reg_539");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, input_0_load_reg_549, "input_0_load_reg_549");
    sc_trace(mVcdFile, add_ln700_fu_453_p2, "add_ln700_fu_453_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, n_0_reg_102, "n_0_reg_102");
    sc_trace(mVcdFile, x_0_reg_114, "x_0_reg_114");
    sc_trace(mVcdFile, icmp_ln63_fu_259_p2, "icmp_ln63_fu_259_p2");
    sc_trace(mVcdFile, y_0_reg_126, "y_0_reg_126");
    sc_trace(mVcdFile, p_014_0_reg_138, "p_014_0_reg_138");
    sc_trace(mVcdFile, c_0_reg_150, "c_0_reg_150");
    sc_trace(mVcdFile, p_014_1_reg_161, "p_014_1_reg_161");
    sc_trace(mVcdFile, r_0_reg_173, "r_0_reg_173");
    sc_trace(mVcdFile, zext_ln68_fu_196_p1, "zext_ln68_fu_196_p1");
    sc_trace(mVcdFile, zext_ln73_3_fu_341_p1, "zext_ln73_3_fu_341_p1");
    sc_trace(mVcdFile, zext_ln68_17_fu_403_p1, "zext_ln68_17_fu_403_p1");
    sc_trace(mVcdFile, zext_ln68_19_fu_434_p1, "zext_ln68_19_fu_434_p1");
    sc_trace(mVcdFile, tmp_fu_205_p3, "tmp_fu_205_p3");
    sc_trace(mVcdFile, zext_ln68_13_fu_213_p1, "zext_ln68_13_fu_213_p1");
    sc_trace(mVcdFile, zext_ln68_12_fu_201_p1, "zext_ln68_12_fu_201_p1");
    sc_trace(mVcdFile, sub_ln68_fu_217_p2, "sub_ln68_fu_217_p2");
    sc_trace(mVcdFile, tmp_s_fu_227_p3, "tmp_s_fu_227_p3");
    sc_trace(mVcdFile, zext_ln65_fu_271_p1, "zext_ln65_fu_271_p1");
    sc_trace(mVcdFile, add_ln68_fu_287_p2, "add_ln68_fu_287_p2");
    sc_trace(mVcdFile, shl_ln1503_fu_301_p2, "shl_ln1503_fu_301_p2");
    sc_trace(mVcdFile, accum_V_fu_307_p2, "accum_V_fu_307_p2");
    sc_trace(mVcdFile, zext_ln73_fu_319_p1, "zext_ln73_fu_319_p1");
    sc_trace(mVcdFile, add_ln73_fu_323_p2, "add_ln73_fu_323_p2");
    sc_trace(mVcdFile, tmp_36_cast_fu_328_p3, "tmp_36_cast_fu_328_p3");
    sc_trace(mVcdFile, add_ln73_2_fu_336_p2, "add_ln73_2_fu_336_p2");
    sc_trace(mVcdFile, zext_ln66_fu_346_p1, "zext_ln66_fu_346_p1");
    sc_trace(mVcdFile, add_ln68_2_fu_362_p2, "add_ln68_2_fu_362_p2");
    sc_trace(mVcdFile, tmp_3_fu_368_p3, "tmp_3_fu_368_p3");
    sc_trace(mVcdFile, tmp_4_fu_380_p3, "tmp_4_fu_380_p3");
    sc_trace(mVcdFile, zext_ln68_15_fu_376_p1, "zext_ln68_15_fu_376_p1");
    sc_trace(mVcdFile, zext_ln68_16_fu_388_p1, "zext_ln68_16_fu_388_p1");
    sc_trace(mVcdFile, add_ln68_9_fu_392_p2, "add_ln68_9_fu_392_p2");
    sc_trace(mVcdFile, add_ln68_10_fu_398_p2, "add_ln68_10_fu_398_p2");
    sc_trace(mVcdFile, zext_ln68_18_fu_408_p1, "zext_ln68_18_fu_408_p1");
    sc_trace(mVcdFile, add_ln68_11_fu_412_p2, "add_ln68_11_fu_412_p2");
    sc_trace(mVcdFile, shl_ln68_fu_417_p2, "shl_ln68_fu_417_p2");
    sc_trace(mVcdFile, sub_ln68_2_fu_423_p2, "sub_ln68_2_fu_423_p2");
    sc_trace(mVcdFile, xor_ln68_fu_438_p2, "xor_ln68_fu_438_p2");
    sc_trace(mVcdFile, xor_ln68_2_fu_444_p2, "xor_ln68_2_fu_444_p2");
    sc_trace(mVcdFile, zext_ln700_fu_449_p1, "zext_ln700_fu_449_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv_1_16_18_s::~conv_1_16_18_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete threshold_conv1_V_U;
    delete w_conv1_0_U;
}

void conv_1_16_18_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_259_p2.read()))) {
        c_0_reg_150 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_350_p2.read(), ap_const_lv1_1))) {
        c_0_reg_150 = c_reg_511.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln62_fu_243_p2.read(), ap_const_lv1_1))) {
        n_0_reg_102 = n_reg_462.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n_0_reg_102 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_259_p2.read()))) {
        p_014_0_reg_138 = ap_const_lv16_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_350_p2.read(), ap_const_lv1_1))) {
        p_014_0_reg_138 = p_014_1_reg_161.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_275_p2.read()))) {
        p_014_1_reg_161 = p_014_0_reg_138.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_014_1_reg_161 = add_ln700_fu_453_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_275_p2.read()))) {
        r_0_reg_173 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_0_reg_173 = r_reg_529.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_259_p2.read()))) {
        x_0_reg_114 = x_reg_490.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_0_reg_114 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln62_fu_243_p2.read()))) {
        y_0_reg_126 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln65_fu_275_p2.read(), ap_const_lv1_1))) {
        y_0_reg_126 = y_reg_503.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_350_p2.read()))) {
        add_ln68_12_reg_539 = add_ln68_12_fu_429_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c_reg_511 = c_fu_281_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_0_load_reg_549 = input_0_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        n_reg_462 = n_fu_190_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_reg_529 = r_fu_356_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sext_ln62_reg_482 = sext_ln62_fu_239_p1.read();
        sext_ln68_reg_472 = sext_ln68_fu_223_p1.read();
        zext_ln895_reg_477 = zext_ln895_fu_235_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_490 = x_fu_249_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_reg_503 = y_fu_265_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln62_fu_243_p2.read()))) {
        zext_ln63_reg_495 = zext_ln63_fu_255_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_275_p2.read()))) {
        zext_ln66_2_reg_521 = zext_ln66_2_fu_297_p1.read();
        zext_ln68_14_reg_516 = zext_ln68_14_fu_293_p1.read();
    }
}

void conv_1_16_18_s::thread_accum_V_fu_307_p2() {
    accum_V_fu_307_p2 = (!ap_const_lv16_FFF7.is_01() || !shl_ln1503_fu_301_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFF7) + sc_biguint<16>(shl_ln1503_fu_301_p2.read()));
}

void conv_1_16_18_s::thread_add_ln68_10_fu_398_p2() {
    add_ln68_10_fu_398_p2 = (!zext_ln68_14_reg_516.read().is_01() || !add_ln68_9_fu_392_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln68_14_reg_516.read()) + sc_biguint<10>(add_ln68_9_fu_392_p2.read()));
}

void conv_1_16_18_s::thread_add_ln68_11_fu_412_p2() {
    add_ln68_11_fu_412_p2 = (!zext_ln68_18_fu_408_p1.read().is_01() || !sext_ln68_reg_472.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln68_18_fu_408_p1.read()) + sc_bigint<9>(sext_ln68_reg_472.read()));
}

void conv_1_16_18_s::thread_add_ln68_12_fu_429_p2() {
    add_ln68_12_fu_429_p2 = (!zext_ln66_2_reg_521.read().is_01() || !sub_ln68_2_fu_423_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln66_2_reg_521.read()) + sc_biguint<9>(sub_ln68_2_fu_423_p2.read()));
}

void conv_1_16_18_s::thread_add_ln68_2_fu_362_p2() {
    add_ln68_2_fu_362_p2 = (!y_0_reg_126.read().is_01() || !zext_ln66_fu_346_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(y_0_reg_126.read()) + sc_biguint<5>(zext_ln66_fu_346_p1.read()));
}

void conv_1_16_18_s::thread_add_ln68_9_fu_392_p2() {
    add_ln68_9_fu_392_p2 = (!zext_ln68_15_fu_376_p1.read().is_01() || !zext_ln68_16_fu_388_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln68_15_fu_376_p1.read()) + sc_biguint<10>(zext_ln68_16_fu_388_p1.read()));
}

void conv_1_16_18_s::thread_add_ln68_fu_287_p2() {
    add_ln68_fu_287_p2 = (!zext_ln65_fu_271_p1.read().is_01() || !x_0_reg_114.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln65_fu_271_p1.read()) + sc_biguint<5>(x_0_reg_114.read()));
}

void conv_1_16_18_s::thread_add_ln700_fu_453_p2() {
    add_ln700_fu_453_p2 = (!zext_ln700_fu_449_p1.read().is_01() || !p_014_1_reg_161.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln700_fu_449_p1.read()) + sc_biguint<16>(p_014_1_reg_161.read()));
}

void conv_1_16_18_s::thread_add_ln73_2_fu_336_p2() {
    add_ln73_2_fu_336_p2 = (!tmp_36_cast_fu_328_p3.read().is_01() || !zext_ln63_reg_495.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_36_cast_fu_328_p3.read()) + sc_biguint<14>(zext_ln63_reg_495.read()));
}

void conv_1_16_18_s::thread_add_ln73_fu_323_p2() {
    add_ln73_fu_323_p2 = (!zext_ln895_reg_477.read().is_01() || !zext_ln73_fu_319_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln895_reg_477.read()) + sc_biguint<10>(zext_ln73_fu_319_p1.read()));
}

void conv_1_16_18_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_1_16_18_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_1_16_18_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln61_fu_184_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln61_fu_184_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_c_fu_281_p2() {
    c_fu_281_p2 = (!c_0_reg_150.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_150.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1_16_18_s::thread_icmp_ln61_fu_184_p2() {
    icmp_ln61_fu_184_p2 = (!n_0_reg_102.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(n_0_reg_102.read() == ap_const_lv5_10);
}

void conv_1_16_18_s::thread_icmp_ln62_fu_243_p2() {
    icmp_ln62_fu_243_p2 = (!x_0_reg_114.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_114.read() == ap_const_lv5_10);
}

void conv_1_16_18_s::thread_icmp_ln63_fu_259_p2() {
    icmp_ln63_fu_259_p2 = (!y_0_reg_126.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_126.read() == ap_const_lv5_10);
}

void conv_1_16_18_s::thread_icmp_ln65_fu_275_p2() {
    icmp_ln65_fu_275_p2 = (!c_0_reg_150.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_150.read() == ap_const_lv2_3);
}

void conv_1_16_18_s::thread_icmp_ln66_fu_350_p2() {
    icmp_ln66_fu_350_p2 = (!r_0_reg_173.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_173.read() == ap_const_lv2_3);
}

void conv_1_16_18_s::thread_input_0_address0() {
    input_0_address0 =  (sc_lv<9>) (zext_ln68_17_fu_403_p1.read());
}

void conv_1_16_18_s::thread_input_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        input_0_ce0 = ap_const_logic_1;
    } else {
        input_0_ce0 = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_n_fu_190_p2() {
    n_fu_190_p2 = (!n_0_reg_102.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(n_0_reg_102.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_1_16_18_s::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<12>) (zext_ln73_3_fu_341_p1.read());
}

void conv_1_16_18_s::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_output_r_d0() {
    output_r_d0 = (!accum_V_fu_307_p2.read().is_01() || !sext_ln62_reg_482.read().is_01())? sc_lv<1>(): (sc_bigint<16>(accum_V_fu_307_p2.read()) > sc_bigint<16>(sext_ln62_reg_482.read()));
}

void conv_1_16_18_s::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_275_p2.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_r_fu_356_p2() {
    r_fu_356_p2 = (!r_0_reg_173.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_173.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1_16_18_s::thread_sext_ln62_fu_239_p1() {
    sext_ln62_fu_239_p1 = esl_sext<16,4>(threshold_conv1_V_q0.read());
}

void conv_1_16_18_s::thread_sext_ln68_fu_223_p1() {
    sext_ln68_fu_223_p1 = esl_sext<9,8>(sub_ln68_fu_217_p2.read());
}

void conv_1_16_18_s::thread_shl_ln1503_fu_301_p2() {
    shl_ln1503_fu_301_p2 = (!ap_const_lv16_1.is_01())? sc_lv<16>(): p_014_0_reg_138.read() << (unsigned short)ap_const_lv16_1.to_uint();
}

void conv_1_16_18_s::thread_shl_ln68_fu_417_p2() {
    shl_ln68_fu_417_p2 = (!ap_const_lv9_2.is_01())? sc_lv<9>(): add_ln68_11_fu_412_p2.read() << (unsigned short)ap_const_lv9_2.to_uint();
}

void conv_1_16_18_s::thread_sub_ln68_2_fu_423_p2() {
    sub_ln68_2_fu_423_p2 = (!shl_ln68_fu_417_p2.read().is_01() || !add_ln68_11_fu_412_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(shl_ln68_fu_417_p2.read()) - sc_biguint<9>(add_ln68_11_fu_412_p2.read()));
}

void conv_1_16_18_s::thread_sub_ln68_fu_217_p2() {
    sub_ln68_fu_217_p2 = (!zext_ln68_13_fu_213_p1.read().is_01() || !zext_ln68_12_fu_201_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln68_13_fu_213_p1.read()) - sc_biguint<8>(zext_ln68_12_fu_201_p1.read()));
}

void conv_1_16_18_s::thread_threshold_conv1_V_address0() {
    threshold_conv1_V_address0 =  (sc_lv<4>) (zext_ln68_fu_196_p1.read());
}

void conv_1_16_18_s::thread_threshold_conv1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        threshold_conv1_V_ce0 = ap_const_logic_1;
    } else {
        threshold_conv1_V_ce0 = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_tmp_36_cast_fu_328_p3() {
    tmp_36_cast_fu_328_p3 = esl_concat<10,4>(add_ln73_fu_323_p2.read(), ap_const_lv4_0);
}

void conv_1_16_18_s::thread_tmp_3_fu_368_p3() {
    tmp_3_fu_368_p3 = esl_concat<5,4>(add_ln68_2_fu_362_p2.read(), ap_const_lv4_0);
}

void conv_1_16_18_s::thread_tmp_4_fu_380_p3() {
    tmp_4_fu_380_p3 = esl_concat<5,1>(add_ln68_2_fu_362_p2.read(), ap_const_lv1_0);
}

void conv_1_16_18_s::thread_tmp_fu_205_p3() {
    tmp_fu_205_p3 = esl_concat<5,2>(n_0_reg_102.read(), ap_const_lv2_0);
}

void conv_1_16_18_s::thread_tmp_s_fu_227_p3() {
    tmp_s_fu_227_p3 = esl_concat<5,4>(n_0_reg_102.read(), ap_const_lv4_0);
}

void conv_1_16_18_s::thread_w_conv1_0_address0() {
    w_conv1_0_address0 =  (sc_lv<8>) (zext_ln68_19_fu_434_p1.read());
}

void conv_1_16_18_s::thread_w_conv1_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        w_conv1_0_ce0 = ap_const_logic_1;
    } else {
        w_conv1_0_ce0 = ap_const_logic_0;
    }
}

void conv_1_16_18_s::thread_x_fu_249_p2() {
    x_fu_249_p2 = (!x_0_reg_114.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x_0_reg_114.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_1_16_18_s::thread_xor_ln68_2_fu_444_p2() {
    xor_ln68_2_fu_444_p2 = (input_0_load_reg_549.read() ^ xor_ln68_fu_438_p2.read());
}

void conv_1_16_18_s::thread_xor_ln68_fu_438_p2() {
    xor_ln68_fu_438_p2 = (w_conv1_0_q0.read() ^ ap_const_lv1_1);
}

void conv_1_16_18_s::thread_y_fu_265_p2() {
    y_fu_265_p2 = (!y_0_reg_126.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y_0_reg_126.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_1_16_18_s::thread_zext_ln63_fu_255_p1() {
    zext_ln63_fu_255_p1 = esl_zext<14,5>(x_0_reg_114.read());
}

void conv_1_16_18_s::thread_zext_ln65_fu_271_p1() {
    zext_ln65_fu_271_p1 = esl_zext<5,2>(c_0_reg_150.read());
}

void conv_1_16_18_s::thread_zext_ln66_2_fu_297_p1() {
    zext_ln66_2_fu_297_p1 = esl_zext<9,2>(c_0_reg_150.read());
}

void conv_1_16_18_s::thread_zext_ln66_fu_346_p1() {
    zext_ln66_fu_346_p1 = esl_zext<5,2>(r_0_reg_173.read());
}

void conv_1_16_18_s::thread_zext_ln68_12_fu_201_p1() {
    zext_ln68_12_fu_201_p1 = esl_zext<8,5>(n_0_reg_102.read());
}

void conv_1_16_18_s::thread_zext_ln68_13_fu_213_p1() {
    zext_ln68_13_fu_213_p1 = esl_zext<8,7>(tmp_fu_205_p3.read());
}

void conv_1_16_18_s::thread_zext_ln68_14_fu_293_p1() {
    zext_ln68_14_fu_293_p1 = esl_zext<10,5>(add_ln68_fu_287_p2.read());
}

void conv_1_16_18_s::thread_zext_ln68_15_fu_376_p1() {
    zext_ln68_15_fu_376_p1 = esl_zext<10,9>(tmp_3_fu_368_p3.read());
}

void conv_1_16_18_s::thread_zext_ln68_16_fu_388_p1() {
    zext_ln68_16_fu_388_p1 = esl_zext<10,6>(tmp_4_fu_380_p3.read());
}

void conv_1_16_18_s::thread_zext_ln68_17_fu_403_p1() {
    zext_ln68_17_fu_403_p1 = esl_zext<64,10>(add_ln68_10_fu_398_p2.read());
}

void conv_1_16_18_s::thread_zext_ln68_18_fu_408_p1() {
    zext_ln68_18_fu_408_p1 = esl_zext<9,2>(r_0_reg_173.read());
}

void conv_1_16_18_s::thread_zext_ln68_19_fu_434_p1() {
    zext_ln68_19_fu_434_p1 = esl_zext<64,9>(add_ln68_12_reg_539.read());
}

void conv_1_16_18_s::thread_zext_ln68_fu_196_p1() {
    zext_ln68_fu_196_p1 = esl_zext<64,5>(n_0_reg_102.read());
}

void conv_1_16_18_s::thread_zext_ln700_fu_449_p1() {
    zext_ln700_fu_449_p1 = esl_zext<16,1>(xor_ln68_2_fu_444_p2.read());
}

void conv_1_16_18_s::thread_zext_ln73_3_fu_341_p1() {
    zext_ln73_3_fu_341_p1 = esl_zext<64,14>(add_ln73_2_fu_336_p2.read());
}

void conv_1_16_18_s::thread_zext_ln73_fu_319_p1() {
    zext_ln73_fu_319_p1 = esl_zext<10,5>(y_0_reg_126.read());
}

void conv_1_16_18_s::thread_zext_ln895_fu_235_p1() {
    zext_ln895_fu_235_p1 = esl_zext<10,9>(tmp_s_fu_227_p3.read());
}

void conv_1_16_18_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln61_fu_184_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln62_fu_243_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_259_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln65_fu_275_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln66_fu_350_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXX";
            break;
    }
}

}

