-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity initialize_padded_me is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_we0 : OUT STD_LOGIC;
    input_r_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of initialize_padded_me is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal m_fu_87_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal m_reg_199 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln41_fu_117_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln41_reg_204 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln38_fu_81_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_129_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_reg_212 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln41_2_fu_164_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_2_reg_217 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln39_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_176_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal m_0_reg_48 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_0_reg_59 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln40_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_0_reg_70 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln41_5_fu_191_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_93_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_105_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln41_1_fu_113_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln41_fu_101_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln41_2_fu_135_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln41_1_fu_139_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_152_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl2_cast_fu_144_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_3_fu_160_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_4_fu_182_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_3_fu_186_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    m_0_reg_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_123_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                m_0_reg_48 <= m_reg_199;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                m_0_reg_48 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    x_0_reg_59_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_fu_170_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                x_0_reg_59 <= x_reg_212;
            elsif (((icmp_ln38_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                x_0_reg_59 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    y_0_reg_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_123_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_0_reg_70 <= ap_const_lv4_0;
            elsif (((icmp_ln40_fu_170_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                y_0_reg_70 <= y_fu_176_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_123_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    add_ln41_2_reg_217(11 downto 1) <= add_ln41_2_fu_164_p2(11 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln38_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    add_ln41_reg_204(8 downto 1) <= add_ln41_fu_117_p2(8 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                m_reg_199 <= m_fu_87_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                x_reg_212 <= x_fu_129_p2;
            end if;
        end if;
    end process;
    add_ln41_reg_204(0) <= '0';
    add_ln41_2_reg_217(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln38_fu_81_p2, ap_CS_fsm_state3, icmp_ln39_fu_123_p2, ap_CS_fsm_state4, icmp_ln40_fu_170_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln38_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln39_fu_123_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln40_fu_170_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln41_1_fu_139_p2 <= std_logic_vector(unsigned(zext_ln41_2_fu_135_p1) + unsigned(add_ln41_reg_204));
    add_ln41_2_fu_164_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_144_p3) + unsigned(zext_ln41_3_fu_160_p1));
    add_ln41_3_fu_186_p2 <= std_logic_vector(unsigned(add_ln41_2_reg_217) + unsigned(zext_ln41_4_fu_182_p1));
    add_ln41_fu_117_p2 <= std_logic_vector(unsigned(zext_ln41_1_fu_113_p1) + unsigned(zext_ln41_fu_101_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln38_fu_81_p2)
    begin
        if ((((icmp_ln38_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln38_fu_81_p2)
    begin
        if (((icmp_ln38_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln38_fu_81_p2 <= "1" when (m_0_reg_48 = ap_const_lv5_10) else "0";
    icmp_ln39_fu_123_p2 <= "1" when (x_0_reg_59 = ap_const_lv4_A) else "0";
    icmp_ln40_fu_170_p2 <= "1" when (y_0_reg_70 = ap_const_lv4_A) else "0";
    input_r_address0 <= zext_ln41_5_fu_191_p1(11 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_r_d0 <= ap_const_lv1_0;

    input_r_we0_assign_proc : process(ap_CS_fsm_state4, icmp_ln40_fu_170_p2)
    begin
        if (((icmp_ln40_fu_170_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            input_r_we0 <= ap_const_logic_1;
        else 
            input_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_fu_87_p2 <= std_logic_vector(unsigned(m_0_reg_48) + unsigned(ap_const_lv5_1));
    p_shl2_cast_fu_144_p3 <= (add_ln41_1_fu_139_p2 & ap_const_lv3_0);
    tmp_2_fu_152_p3 <= (add_ln41_1_fu_139_p2 & ap_const_lv1_0);
    tmp_fu_93_p3 <= (m_0_reg_48 & ap_const_lv3_0);
    tmp_s_fu_105_p3 <= (m_0_reg_48 & ap_const_lv1_0);
    x_fu_129_p2 <= std_logic_vector(unsigned(x_0_reg_59) + unsigned(ap_const_lv4_1));
    y_fu_176_p2 <= std_logic_vector(unsigned(y_0_reg_70) + unsigned(ap_const_lv4_1));
    zext_ln41_1_fu_113_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_105_p3),9));
    zext_ln41_2_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_0_reg_59),9));
    zext_ln41_3_fu_160_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_152_p3),12));
    zext_ln41_4_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_0_reg_70),12));
    zext_ln41_5_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_3_fu_186_p2),64));
    zext_ln41_fu_101_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_93_p3),9));
end behav;
