// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module flatten (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] input_r_address0;
output   input_r_ce0;
input  [0:0] input_r_q0;
output  [8:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [0:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] zext_ln112_fu_96_p1;
reg   [8:0] zext_ln112_reg_217;
wire    ap_CS_fsm_state2;
wire   [5:0] c_fu_106_p2;
reg   [5:0] c_reg_225;
wire   [8:0] zext_ln113_fu_120_p1;
reg   [8:0] zext_ln113_reg_230;
wire   [0:0] icmp_ln112_fu_100_p2;
wire   [2:0] y_fu_130_p2;
reg   [2:0] y_reg_238;
wire    ap_CS_fsm_state3;
wire   [10:0] tmp_21_cast_fu_145_p3;
reg   [10:0] tmp_21_cast_reg_243;
wire   [0:0] icmp_ln113_fu_124_p2;
wire   [3:0] shl_ln_fu_157_p3;
reg   [3:0] shl_ln_reg_248;
wire   [2:0] x_fu_171_p2;
reg   [2:0] x_reg_256;
wire    ap_CS_fsm_state4;
wire   [8:0] o_index_fu_194_p2;
reg   [8:0] o_index_reg_261;
wire   [0:0] icmp_ln114_fu_165_p2;
reg   [5:0] c_0_reg_63;
reg   [2:0] y_0_reg_74;
reg   [2:0] x_0_reg_85;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln116_2_fu_208_p1;
wire   [63:0] zext_ln116_3_fu_213_p1;
wire   [7:0] tmp_fu_112_p3;
wire   [8:0] zext_ln116_fu_136_p1;
wire   [8:0] add_ln116_fu_140_p2;
wire   [1:0] trunc_ln115_fu_153_p1;
wire   [3:0] zext_ln115_fu_177_p1;
wire   [3:0] add_ln115_fu_181_p2;
wire   [8:0] shl_ln115_1_fu_186_p3;
wire   [10:0] zext_ln116_1_fu_199_p1;
wire   [10:0] add_ln116_1_fu_203_p2;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        c_0_reg_63 <= c_reg_225;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_0_reg_63 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        x_0_reg_85 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_0_reg_85 <= x_reg_256;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln114_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        y_0_reg_74 <= y_reg_238;
    end else if (((icmp_ln112_fu_100_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_0_reg_74 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        c_reg_225 <= c_fu_106_p2;
        zext_ln112_reg_217[5 : 0] <= zext_ln112_fu_96_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln114_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        o_index_reg_261 <= o_index_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        shl_ln_reg_248[3 : 2] <= shl_ln_fu_157_p3[3 : 2];
        tmp_21_cast_reg_243[10 : 2] <= tmp_21_cast_fu_145_p3[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_reg_256 <= x_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_reg_238 <= y_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln112_fu_100_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln113_reg_230[7 : 2] <= zext_ln113_fu_120_p1[7 : 2];
    end
end

always @ (*) begin
    if ((((icmp_ln112_fu_100_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln112_fu_100_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln112_fu_100_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln113_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln114_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_fu_181_p2 = (shl_ln_reg_248 + zext_ln115_fu_177_p1);

assign add_ln116_1_fu_203_p2 = (zext_ln116_1_fu_199_p1 + tmp_21_cast_reg_243);

assign add_ln116_fu_140_p2 = (zext_ln116_fu_136_p1 + zext_ln113_reg_230);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign c_fu_106_p2 = (c_0_reg_63 + 6'd1);

assign icmp_ln112_fu_100_p2 = ((c_0_reg_63 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_124_p2 = ((y_0_reg_74 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_165_p2 = ((x_0_reg_85 == 3'd4) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln116_2_fu_208_p1;

assign o_index_fu_194_p2 = (shl_ln115_1_fu_186_p3 + zext_ln112_reg_217);

assign output_r_address0 = zext_ln116_3_fu_213_p1;

assign output_r_d0 = input_r_q0;

assign shl_ln115_1_fu_186_p3 = {{add_ln115_fu_181_p2}, {5'd0}};

assign shl_ln_fu_157_p3 = {{trunc_ln115_fu_153_p1}, {2'd0}};

assign tmp_21_cast_fu_145_p3 = {{add_ln116_fu_140_p2}, {2'd0}};

assign tmp_fu_112_p3 = {{c_0_reg_63}, {2'd0}};

assign trunc_ln115_fu_153_p1 = y_0_reg_74[1:0];

assign x_fu_171_p2 = (x_0_reg_85 + 3'd1);

assign y_fu_130_p2 = (y_0_reg_74 + 3'd1);

assign zext_ln112_fu_96_p1 = c_0_reg_63;

assign zext_ln113_fu_120_p1 = tmp_fu_112_p3;

assign zext_ln115_fu_177_p1 = x_0_reg_85;

assign zext_ln116_1_fu_199_p1 = x_0_reg_85;

assign zext_ln116_2_fu_208_p1 = add_ln116_1_fu_203_p2;

assign zext_ln116_3_fu_213_p1 = o_index_reg_261;

assign zext_ln116_fu_136_p1 = y_0_reg_74;

always @ (posedge ap_clk) begin
    zext_ln112_reg_217[8:6] <= 3'b000;
    zext_ln113_reg_230[1:0] <= 2'b00;
    zext_ln113_reg_230[8] <= 1'b0;
    tmp_21_cast_reg_243[1:0] <= 2'b00;
    shl_ln_reg_248[1:0] <= 2'b00;
end

endmodule //flatten
